name: student_booking_app
description: "Student Booking Flutter App with Google Sign-In"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.5.4
  google_sign_in: ^6.1.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"